name = "Hugo Toast"
license = "MIT"
licenselink = ""
description = "Hugo theme for Toastmaster's club like site"
homepage = ""
tags = ["blog","responsive","personal","google analytics","portfolio","disqus","bootstrap","font awesome","projects","creative","landing page","product","white","share this"]
features = ["blog","responsive","personal","google analytics","portfolio","disqus","bootstrap","font awesome","projects","creative","landing page","product","white","share this"]
min_version = "0.1"

[author]
  name = "Aymeric Gerardin"
  homepage = "https://aymericgerardin.github.io/hugo-toast-site/"

[original]
  name = "Hugo-initio"
  author = "Miguel Simoni"
  homepage = "https://miguelsimoni.github.io/hugo-initio-site/"
  repo = "https://github.com/miguelsimoni/hugo-initio.git"
